version: '3.8'

services:
  nginx:
    build: ./infrastructure/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi
      - dashboard
      - landing
    volumes:
      - ./infrastructure/nginx:/etc/nginx

  fastapi:
    build: ./services/fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./services/fastapi:/app

  worker:
    build: ./services/worker
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    volumes:
      - ./services/worker:/app

  scheduler:
    build: ./services/scheduler
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    volumes:
      - ./services/scheduler:/app


  dashboard:
    build: ./frontend/dashboard
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/dashboard:/app
      - /app/node_modules

  landing:
    build: ./frontend/landing
    ports:
      - "3002:3000"
    volumes:
      - ./frontend/landing:/app
      - /app/node_modules

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: careremind
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  prometheus:
    image: prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3003:3000"
    volumes:
      - ./monitoring/grafana:/etc/grafana

volumes:
  postgres_data:
