import client from './client';

export const bookingApi = {
  // Get all clinic locations for booking
  getClinics: () => client.get('/booking/clinics'),

  // Get available slots for a specific date and clinic
  getSlots: (clinicLocationId: string, bookingDate: string) =>
    client.get('/booking/slots', {
      params: { clinic_location_id: clinicLocationId, booking_date: bookingDate },
    }),

  // Reserve a slot (temporary hold for 10 minutes)
  reserveSlot: (data: {
    clinic_location_id: string;
    booking_date: string;
    slot_time: string;
    patient_id: string;
  }) => client.post('/booking/reserve', data),

  // Confirm booking after payment
  confirmBooking: (data: {
    booking_id: string;
    razorpay_payment_id: string;
    razorpay_order_id: string;
    razorpay_signature: string;
  }) => client.post('/booking/confirm', data),

  // Cancel a booking
  cancelBooking: (data: { booking_id: string; reason?: string }) =>
    client.post('/booking/cancel', data),

  // Get daily schedule PDF URL for a specific date (pre-generated by cron)
  getSchedule: (date: string) => client.get(`/booking/schedule/${date}`),

  // Get current user's bookings
  getMyBookings: (page = 1, perPage = 20) =>
    client.get('/booking/my-bookings', {
      params: { page, per_page: perPage },
    }),

  // ── Doctor Dashboard ─────────────────────────────────────────────────────

  /**
   * List confirmed bookings for a given date enriched with patient + clinic names.
   * Used by the Bookings dashboard page (live auto-refreshing table).
   */
  listBookings: (bookingDate?: string, clinicLocationId?: string) =>
    client.get('/booking/list', {
      params: {
        ...(bookingDate ? { booking_date: bookingDate } : {}),
        ...(clinicLocationId ? { clinic_location_id: clinicLocationId } : {}),
      },
    }),

  /**
   * Build a URL for the on-demand schedule PDF download.
   * Token is passed as a query param because browser-initiated anchor downloads
   * cannot set Authorization headers.
   */
  getSchedulePdfUrl: (bookingDate: string, clinicLocationId?: string): string => {
    const token = localStorage.getItem('token') ?? '';
    const base = (
      (import.meta.env.VITE_API_URL as string | undefined) ?? 'http://localhost:8000/api/v1'
    ).replace(/\/$/, '');
    const params = new URLSearchParams({ booking_date: bookingDate });
    if (clinicLocationId) params.set('clinic_location_id', clinicLocationId);
    if (token) params.set('token', token);
    return `${base}/booking/download-pdf?${params.toString()}`;
  },
};
